CREATE TABLE [dbo].[REPORT_DATA_GROUP_SIGNOFF] (
    [ASOFDATE]             DATE           NOT NULL,
    [REPORT_DATA_GROUP_ID] INT            NOT NULL,
    [RAG]                  VARCHAR (1)    NOT NULL,
    [SIGNOFF_COMMENT]      NVARCHAR (500) NULL,
    [USER_ID]              NVARCHAR (6)   NULL,
    [SIGNOFF_DATETIME]     DATETIME       NULL,
    CONSTRAINT [pk_REPORT_DATA_GROUP_SIGNOFF] PRIMARY KEY CLUSTERED ([ASOFDATE] ASC, [REPORT_DATA_GROUP_ID] ASC),
    CONSTRAINT [chk_REPORT_DATA_GROUP_SIGNOFF] CHECK ([RAG]='N' OR [RAG]='G' OR [RAG]='A' OR [RAG]='R')
);

