CREATE TABLE [dbo].[REPORT_DATA_GROUP] (
    [REPORT_DATA_GROUP_ID]   INT            NOT NULL,
    [REPORT_DATA_GROUP_NAME] NVARCHAR (100) NULL,
    [START_DATE]             DATE           NOT NULL,
    [END_DATE]               DATE           NOT NULL,
    CONSTRAINT [pk_REPORT_DATA_GROUP] PRIMARY KEY CLUSTERED ([REPORT_DATA_GROUP_ID] ASC, [START_DATE] ASC)
);

